version: "3.9"
services:
  api_db:
    image: postgres:13-alpine
    container_name: api_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapidb
    volumes:
      - fastapi-data:/var/lib/postgres/data
  api:
    build: .
    container_name: api
    restart: unless-stopped
    command: >
      bash -c "aerich init -t app.api.api_v1.settings.TORTOISE_ORM
      && aerich init-db 
      && python main.py"
    ports:
      - 8000:80
    depends_on:
      - api_db
volumes:
  fastapi-data:
    driver: local
